# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 29 May 2017 12:21:21 +0000
*	@ALL	1
*	@user	0
anmeldung	@anmeldung	1
anmeldung	@ALL	0
anmeldung	@admin	2
anmeldung	@admin%5fanmeldung	2
catering	@ALL	0
catering	@admin	2
catering	@catering	1
catering	@admin%5fcatering	2
catering	@catering%5fadmin	2
einladungen	@ALL	0
einladungen	@admin	2
einladungen	@einladungen	1
einladungen	@einladungen%5fadmin	2
flyer	@admin	2
flyer	@ALL	0
flyer	@flyer	1
flyer	@flyer%5fadmin	2
raumplanung	@ALL	0
raumplanung	@admin	2
raumplanung	@raumplanung	1
raumplanung	@raumplanung%5fadmin	2
vortrag	@ALL	0
vortrag	@admin	2
vortrag	@vortrag	1
vortrag	@vortrag%5fadmin	2
sidebar	@ALL	0
sidebar	@admin	2
sidebar	@admin%5fcatering	1
sidebar	@admin%5fanmeldung	1
sidebar	@anmeldung	1
sidebar	@catering	1
sidebar	@catering%5fadmin	1
sidebar	@einladungen	1
sidebar	@einladungen%5fadmin	1
sidebar	@flyer	1
sidebar	@flyer%5fadmin	1
sidebar	@raumplanung	1
sidebar	@raumplanung%5fadmin	1
sidebar	@vortrag	1
sidebar	@vortrag%5fadmin	1
