<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Mon, 29 May 2017 14:47:42 +0200
 */

$conf['title'] = 'TDWI';
$conf['lang'] = 'de';
$conf['template'] = 'greensteel';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';

// end auto-generated content
